name: lindol-ph

secrets:
  usgs_url:
    file: ./secrets/usgs_url.txt

services:
  web:
    container_name: lindol-ph-app
    image: lindol-ph:latest
    build:
      context: .
      secrets:
        - usgs_url
    ports:
      - "3000:3000"
    env_file:
      - .env.local
